### PR TITLE
chore(docs) add info on thomas

### PR DESCRIPTION
**Pull request by thogli**
This is an exercise in terminal command patience

### CODE REVIEW

**Review by axelolsson — APPROVED** [review]
LGTM +1

**Comment by cillaTufvesson** [comment]
Missing a colon, shouldn't the tool help with that?

**Review by cillaTufvesson — APPROVED** [review]
Colon not that important to me :-)

**Review by axelolsson — CHANGES_REQUESTED** [review]
Actually @cillaTufvesson is right, the colon needs to be here to separate type(scope) from the subject line in the commit message.

Please fix @thogli

**Pull request merged**
