### PR TITLE
docs: add cilla as contributor

### PR DESCRIPTION
**Pull request by cillaTufvesson**
Just do what Axel wanted :-)

### CODE REVIEW

**Comment by cillaTufvesson** [comment]
Hrm I as always made spelling error so in git commit it's wrong but hoping that correcting in git UI will do it or will it cause problems?

**Comment by pettax** [comment]
> Hrm I as always :-( made a spelling error. So in git commit it's wrong but hoping that correcting in git UI will do it or will it cause problems?
> 
> And why do I have two icons and not only one, what did I do wrong now :-(
> Screenshot 2021-01-28 at 15 45 22

It could be that you have two different email-addresses at play. One in your local git configuration and one here on your github user.

**Comment by cillaTufvesson** [comment]
> It could be that you have two different email-addresses at play. One in your local git configuration and one here on your github user.

Aha, yes it is, thanks

**Review by axelolsson — CHANGES_REQUESTED** [review]
@cillaTufvesson regarding the commit message - you would have to `amend` the commit message locally I'm afraid.

1. `git clone` the repo
2. checkout you branch `docs/add-cilla`
3. `git commit --amend` - will bring up vim where you can edit the message.
4. Once you're done there, you'll need to `git push -f` your locally edited history to the remote `docs/add-cilla` branch.

**Comment by cillaTufvesson** [comment]
Can we try not to, because I think it will take my message in this UI ?
At least that's how I think it worked at last place. Would be good to know and also now I know the command on how to fix da shit.

Screenshot 2021-01-29 at 08 57 59

**Comment by axelolsson** [comment]
> Can we try not to, because I think it will take my message in this UI ?
> At least that's how I think it worked at last place. Would be good to know and also now I know the command on how to fix da shit.
> 
> Screenshot 2021-01-29 at 08 57 59

The message will be shown for the PR-merge yes, but the _commit_ will still be incorrect in the git log. :)

**Comment by cillaTufvesson** [comment]
done

**Review by axelolsson — APPROVED** [review]
LGTM 👍

**Pull request merged**
