### PR TITLE
feat/[github-meeting]/carlos_contribution: little test

### PR DESCRIPTION
**Pull request by cgarridomurillogithub**
Let's rock with this little test !

### CODE REVIEW

**Comment by cgarridomurillogithub** [comment]
I just put w/e in the file, nice hah :D

**Review by axelolsson — CHANGES_REQUESTED** [review]
Nice @cgarridomurillogithub - but your commit shouldn't have passed the linter locally.

Did you?:
- `npm install`
- `git commit`

**Comment by cgarridomurillogithub** [comment]
> Nice @cgarridomurillogithub - but your commit shouldn't have passed the linter locally.
> 
> Did you?:
> 
> * `npm install`
> * `git commit`

yup! maybe old repository stuff! I will do it again

**Comment by cgarridomurillogithub** [comment]
npm install
git commit

done!

**Review by axelolsson — APPROVED** [review]
@cgarridomurillogithub as long as we squash these it will be fine.

But, here's how I would write the commit:

`docs(carlos): add carlos to contributors`

**Comment by cgarridomurillogithub** [comment]
> @cgarridomurillogithub as long as we squash these it will be fine.
> 
> But, here's how I would write the commit:
> 
> `docs(carlos): add carlos to contributors`

And what about creating a poll to set some conventions on branches, commits, etc ?

**Comment by axelolsson** [comment]
> > @cgarridomurillogithub as long as we squash these it will be fine.
> > But, here's how I would write the commit:
> > `docs(carlos): add carlos to contributors`
> 
> And what about creating a poll to set some conventions on branches, commits, etc ?

Good point. Maybe we can set something up for next week. Perhaps a simple google form with alternatives?

**Pull request merged**
